# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4db5595993f2ca99f2e2a7d9635c7d53f8cdbd5d0f16c5fe9f321a273a8784df1ae60383614b3176a11a51988b12833fbcc960398ad690ada34046d64af880db

test:
  secret_key_base: 890693531e6a7a98c32e49561046ae10d6cf9a6f20c9c7046b6d12b4f4b5ff1ced79f2d43df19a5231e1ba47ce7e58b04db3cdc541d1fb82f3b1c3828cd5ce83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
